export enum PaymentMethod {
  TRANSFERENCIA = 'Transferencia Bancaria',
  PAGO_MOVIL = 'Pago Móvil',
  ZELLE = 'Zelle',
  BINANCE = 'Binance',
  EFECTIVO_BS = 'Efectivo Bs',
  EFECTIVO_USD = 'Efectivo $',
  EFECTIVO_EUR = 'Efectivo Euro'
}

export enum EducationLevel {
  MATERNAL = 'Maternal',
  PREESCOLAR_1 = 'Pre-escolar 1er Nivel',
  PREESCOLAR_2 = 'Pre-escolar 2do Nivel',
  PREESCOLAR_3 = 'Pre-escolar 3er Nivel',
  PRIMARIA_1 = 'Primaria 1er Grado',
  PRIMARIA_2 = 'Primaria 2do Grado',
  PRIMARIA_3 = 'Primaria 3er Grado',
  PRIMARIA_4 = 'Primaria 4to Grado',
  PRIMARIA_5 = 'Primaria 5to Grado',
  PRIMARIA_6 = 'Primaria 6to Grado',
  SECUNDARIA_1 = 'Secundaria 1er Año',
  SECUNDARIA_2 = 'Secundaria 2do Año',
  SECUNDARIA_3 = 'Secundaria 3er Año',
  SECUNDARIA_4 = 'Secundaria 4to Año',
  SECUNDARIA_5 = 'Secundaria 5to Año'
}

export interface PaymentRecord {
  id: string; // Col A: paymentId
  // timestamp generated by server
  registrationDate: string; // Col C
  paymentDate: string; // Col D
  representativeId: string; // Col E: representativeCi
  studentName: string; // Col F: studentId (Mapped to Name based on image data)
  paidMonths: string[]; // Col G: month
  schoolYear: string; // Col H: year
  paymentMethod: PaymentMethod; // Col I
  referenceNumber: string; // Col J
  amount: number; // Col K
  // status generated by server (Col L)
  description?: string; // Col M: observations
  representativeName: string; // Col N
  studentMatricula: string; // Col O: matricula
  level: EducationLevel; // Not explicitly in image columns but needed for logic, maybe put in observations or month
}

export interface DebtStatus {
  month: string;
  amount: number;
  status: 'Pendiente' | 'Pagado' | 'Vencido';
  dueDate?: string;
}

export interface ReportFilter {
  month?: string;
  startDate?: string;
  endDate?: string;
  level?: string;
  paymentMethod?: string;
}

export interface ReportResult {
  totalAmount: number;
  count: number;
  breakdown: {
    category: string;
    amount: number;
  }[];
}

export interface User {
  cedula: string;
  name: string;
  role?: string;
}