export enum PaymentMethod {
  TRANSFERENCIA = 'Transferencia Bancaria',
  PAGO_MOVIL = 'Pago Móvil',
  ZELLE = 'Zelle',
  BINANCE = 'Binance',
  EFECTIVO_BS = 'Efectivo Bs',
  EFECTIVO_USD = 'Efectivo $',
  EFECTIVO_EUR = 'Efectivo Euro'
}

export interface Student {
  matricula: string;
  studentName: string;
}

export interface PaymentRecord {
  id: string;                // Col A: paymentId
  // timestamp (Col B) is generated by server
  registrationDate: string;  // Col C
  paymentDate: string;       // Col D
  representativeCedula: string; // Col E
  studentName: string;       // Col F: studentId (Mapped to Name)
  paidMonths: string[];      // Col G: month
  schoolYear: string;        // Col H: year
  paymentMethod: PaymentMethod; // Col I
  referenceNumber: string;   // Col J
  amountUSD: number;         // Col K: amount$
  amountBs: number;          // Col L: amountBs
  // status (Col M) is generated by server
  description?: string;      // Col N: observations
  representativeName: string;// Col O
  studentMatricula: string;  // Col P
  paymentForm: string;       // Col Q: paymentForm (e.g. "Total", "Abono")
}

export interface DebtStatus {
  month: string;
  amount: number;
  status: 'Pendiente' | 'Pagado' | 'Vencido';
  dueDate?: string;
}

export interface ReportFilter {
  month?: string;
  startDate?: string;
  endDate?: string;
  paymentMethod?: string;
}

export interface ReportResult {
  totalAmount: number;
  count: number;
  breakdown: {
    category: string;
    amount: number;
  }[];
}

export interface User {
  cedula: string;
  name: string;
  role?: string;
}